language: ruby
branches:
- gh-pages
rvm:
- 2.1
script: "bundle exec jekyll build"

deploy:
  provider: pages
  local_dir: _site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

